// <auto-generated />
using System;
using BlizzardWebApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlizzardWebApp.Server.Migrations
{
    [DbContext(typeof(LbDbContext))]
    [Migration("20260519183704_AddDbSetAffixes")]
    partial class AddDbSetAffixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BlizzardWebApp.Server.Data.Affixes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Affixes");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.ConnectedRealmsDb", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auctions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MythicLeaderboard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConnectedRealms");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeystoneLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeaderboardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ranking")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.KeystoneLeaderboard.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "MemberId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MemberId");

                    b.ToTable("GroupMember");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Leaderboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastFetchTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaderboardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardId");

                    b.ToTable("KeystoneLeaderboards");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Realm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.LeaderboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Lost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("LeaderboardEntry");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.LeaderboardSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePulled")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LeaderboardSnapshots");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.MythicKeystoneDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DungeonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Keystones");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.RealmDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CRealmsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CRealmsId");

                    b.HasIndex("Name");

                    b.ToTable("RealmDb");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Group", b =>
                {
                    b.HasOne("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Leaderboard", "Leaderboard")
                        .WithMany("LeadingGroups")
                        .HasForeignKey("LeaderboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.KeystoneLeaderboard.GroupMember", b =>
                {
                    b.HasOne("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Member", "Member")
                        .WithMany("GroupMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.LeaderboardEntry", b =>
                {
                    b.HasOne("BlizzardWebApp.Server.Data.LeaderboardSnapshot", "Snapshot")
                        .WithMany("Entries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.RealmDb", b =>
                {
                    b.HasOne("BlizzardWebApp.Server.Data.ConnectedRealmsDb", "ConnectedRealm")
                        .WithMany("Realms")
                        .HasForeignKey("CRealmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedRealm");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.ConnectedRealmsDb", b =>
                {
                    b.Navigation("Realms");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Group", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Leaderboard", b =>
                {
                    b.Navigation("LeadingGroups");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.KeystoneLeaderboard.Member", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("BlizzardWebApp.Server.Data.LeaderboardSnapshot", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
